<?php $this->placeholder('multiscripts')->captureStart();?>

<script>
  
    $(document).ready(function(){
			
	$( "#tabs" ).tabs({});
	alert('aqui');
			
    });



</script>


<?php $this->placeholder('multiscripts')->captureEnd() ?>

<form id="form1" name="form1">
  		<div id="tabs">
  				
  				 <div class="form l300" style="width:3oopx;">
  				 
                <ul> 
                    <li><a href="#tabs-1">Teste</a></li> 
                </ul> 
                <div id="tabs-1"> 
                </div>
                </div>
                </div>
                </form>

