<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="noindex,nofollow">

<title>Termos de uso</title>



<script type="text/javascript" src="/assets/portal/default/scripts/bValidator-0.6/jquery-1.7.2.min.js"></script>

<style>

#caixatexto
{
	width:400px;
	height:300px;
	overflow-y:scroll;
	text-align:justify;
	padding:5px;
	overflow:scroll;
}

#botoes
{
	margin-top:20px;
	width:400px;
}
h3
{
	font-weight:bold;
}
</style>

</head>

<body>

<div id="caixatexto">
<h3>Termos de uso</h3>
<p>
Bem-vindo aos nossos sites, disponibilizados para você pela empresa Invento Novo, escritório registrado
em Araxa - MG. Estes termos de uso (doravante denominados "termos de uso") governam o uso que você
faz de nossos produtos em todas as páginas da Web que fazem parte dele e todo conteúdo, software e
serviço neles oferecidos (doravante chamadosde "sites").
</p>

<p>
O uso que você faz de nossos sites significa que você aceita estes Termos de uso, que você consente
com nossa política de privacidade (doravante denominada "Política de privacidade"), e que você aceita
receber as notificações necessárias e interagir quando necessário.
</p>


<p>
Caso você não concorde com os termos de uso e/ou a política de privacidade, aconselhamos que não
use nossos produtos.
</p>

<p>
1. MUDANÇAS NOS TERMOS DE USO
Nós podemos mudar estes termos de uso a qualquer momento. Você pode revisar a versão mais atual
clicando no link "termos de uso" localizado na parte inferior dos sites. Você é responsável por verificar
periodicamente se houve mudanças nos termos de uso. Se você continuar usando os sites depois que
publicarmos mudanças nos Termos de Uso, você indicará que aceitou as novas condições.

</p>

<p>

2. TERMOS ADICIONAIS
Certas áreas dos sites, como a área de fotos e vídeos pode incluir diretriz e regras que complementarão
estes Termos de uso. Ao usar estes serviços nos sites, você concorda em cumprir com as diretrizes e
regras.

</p>

<p>

3. POLÍTICA DE ENTREGA ELETRÔNICA E SEU CONSENTIMENTO.
Você concorda que nós possamos fornecer a você eletronicamente avisos, acordos e outras informações
solicitadas relacionadas aos sites. Se você não mais concordar em receber eletronicamente os avisos,
cancele o uso dos sites, porém a Invento Novo repudia o uso de spam por respeito aos seus usuários.

</p>

<p>

4. POLÍTICA DE PRIVACIDADE.
A Política de privacidade explica as práticas que se aplicam às suas informações pessoais quando você
usa o site. O uso contínuo dos sites indica seu consentimento com as práticas de informação divulgadas
em nossa Política de privacidade. Você pode revisar a Política de privacidade a qualquer momento
clicando no link da Política de privacidade localizado na parte inferior dos sites.

</p>

<p>
5. MUDANÇAS NOS SITES
Nós podemos descontinuar ou mudar qualquer serviço ou recurso dos sites a qualquer momento e sem
prévio aviso.

</p>
<p>
6. CUSTOS DE ACESSO
Você deve fornecer às suas próprias custas o equipamento e as conexões de Internet de que precisará
para acessar e usar os sites. Se você acessar os sites por uma linha telefônica, fale com sua companhia
telefônica local para determinar se os números de acesso que você seleciona estão sujeitos a tarifas de
longa distância ou outros custos de ligação em seu local. Além disso, se você acessar os sites da Web
por meio de dispositivos sem fios (por exemplo, telefone celular), a sua operadora, como uma operadora
sem fios, por exemplo, pode cobrar taxas por alertas, navegação da web, mensagens e outros serviços
que requerem o uso de tempo de conexão e serviços de dados sem fios. Consulte sua operadora para
verificar se alguma dessas tarifas se aplica a você. Você é o único responsável por quaisquer custos
incorridos para acessar os sites usando qualquer serviço de comunicação sem fios ou de outros meios.
</p>
<p>
7. SUAS RESPONSABILIDADES
</p>

<p>
7.1 Você só pode usar os sites para propósitos legais. Você pode não submeter ou transmitir pelos sites
quaisquer informações, conteúdo ou material, ou se dedicar a qualquer conduta que:
</p>
<p>
1. Viole ou infrinja os direitos dos outros, incluindo, sem limitação a, patentes, marcas registradas,
segredos comerciais, direitos autorais, publicidade, ou outros direitos de propriedade;
</p>
<p>
2. For ilegal, ameaçadora, abusiva, molestadora, difamatória, caluniosa, enganosa, fraudulenta, invasiva
da privacidade de outros, errada, ou que contenha descrições explícitas ou gráficas, ou relatos de, atos
sexuais, pedofilia e ou pornográfica
</p>
<p>
3. Vitimize, moleste, degrade ou intimide um indivíduo ou grupo de indivíduos com base em religião,
gênero, orientação sexual, raça, etnia, idade ou deficiência;
</p>
<p>
4. Personifique qualquer pessoa, empresa ou entidade, incluindo a Invento Novo e seus funcionários e
agentes;
</p>
<p>
5. Contenha vírus ou qualquer outro código de computador, arquivos ou programas que interrompam,
destruam ou limitem a funcionalidade de qualquer software de computador ou hardware ou equipamento
de telecomunicações, ou que, de outra forma, permita o uso não autorizado de um computador ou de uma
rede de computadores;
</p>
<p>
6. Encoraje uma conduta que se constitua em delito penal, ou que dê origem a responsabilidade civil;
</p>
<p>
7. Viole estes Termos de uso, diretrizes ou qualquer política publicada nos sites; ou
</p>
<p>
8. Interfira com o uso dos sites feito por outros.
</p>
<p>
7.2 Você não pode usar nossos sites:
</p>
<p>
1. Para obter lucro comercial para si próprio;
</p>
<p>
2. Para oferecer qualquer forma de anúncio ou promoção sem nosso consentimento prévio por escrito; ou
</p>
<p>
3. Para fornecer, sem permissão, quaisquer informações pessoais falsas ou quaisquer informações,
conteúdo ou material sobre qualquer outra pessoa que não seja você.
</p>
<p>
7.3 Ao usar nosso produto, você concorda em:
</p>
<p>
1. Cumprir estes Termos de uso;
</p>
<p>
2. Manter suas informações de contato precisas e atualizadas;
</p>
<p>
3. não compartilhar ou transferir sua senha sem nosso consentimento.
</p>
<p>
7.4 Você não pode usar os sites de qualquer maneira que possa danificar, incapacitar, sobrecarregar ou
prejudicar nossos servidores e redes, ou interferir com o uso dos sites por outras partes. Você não pode
tentar obter acesso não autorizado a qualquer serviço, contas do usuário, sistemas de computador ou
redes, por meio de hacking, quebra de senhas ou quaisquer outros meios. Nós podemos adotar qualquer
medida legal e técnica para impedir a violação destas provisões e fazer cumprir estes termos de uso.
</p>
<p>
Cada usuário pode ter somente uma conta. Reservamos o direito de excluir ou suspender
temporariamente uma conta se encontrarmos usuários com contas múltiplas, ou por qualquer outro
motivo para investigação.
</p>
<p>
7.5 Você não pode usar o nosso produto ou quaisquer de nossas ferramentas de comunicação para
transmitir, direta ou indiretamente, qualquer comunicação de massa não solicitada (incluindo e-mails e
mensagens instantâneas). Você não pode coletar informações sobre nossos usuários com a finalidade de
enviar (ou facilitar o envio) de comunicações de massa não solicitadas. Você não pode induzir ou permitir
que outros usem os sites para violar os termos desta seção. Nós podemos cancelar seu acesso ou uso
dos sites imediatamente e adotar outra ação legal se você, ou qualquer um que use seu acesso aos sites,
violar estas disposições. Nós podemos adotar qualquer medida técnica para impedir a entrada, solicitação
ou permanência de comunicações de massa não solicitadas em nossos computadores ou nossas redes
de comunicação.
</p>
<p>
7.6 Quaisquer informações, conteúdo ou material que você tenha criado e submetido ou transmitido
pelos sites que estiver protegido por direitos de propriedade intelectual (ou direitos semelhantes) deve
ser licenciado para nós como uma licença não exclusiva, transferível, sublicenciável, livre de royalties,
perpétua e de âmbito mundial, e nós teremos o direito de usar essa propriedade intelectual referente aos
sites, ou qualquer outro meio.
</p>
<p>
7.7 Quando você fornece informações, conteúdo ou material e usa a configuração de privacidade pública,
isso significa que todos os visitantes dos sites terão acesso a essas informações e que nós não teremos
controle sobre essas informações ou sobre o que os visitantes fazem com elas.
</p>
<p>
7.8 Reservamo-nos o direito de remover quaisquer informações, conteúdos ou material dos sites caso
violem estes Termos de uso.
</p>
<p>
7.9 Se você selecionar um nome de usuário, reservamo-nos o direito de removê-lo ou retomá-lo se
considerarmos apropriado.
</p>
<p>
8. LICENÇA DE USO DOS SITES
Sujeito a estes Termos de uso, você pode usar os sites e o conteúdo oferecido por nossos produtos
apenas para propósitos pessoais e não comerciais. Você pode usar o conteúdo oferecido para fazer uso
pessoal apenas e que está sujeito às regras que se aplicarem àquele conteúdo específico. Você não pode
usar o conteúdo de maneira que ultrapasse os direitos concedidos a você para uso do conteúdo. Você
não pode usar quaisquer ferramentas de mineração de dados, robôs, ou aplicar ferramentas de coleta e
extração de dados ao conteúdo; copiar qualquer parte dos sites ou conteúdo, ou reproduzir, reimprimir,
copiar, armazenar, exibir publicamente, radiodifundir, transmitir, modificar, traduzir, portar, publicar,
sublicenciar, ceder, transferir, vender, emprestar, ou, de outra forma, distribuir o conteúdo sem nosso
consentimento prévio por escrito. Você não pode contornar qualquer mecanismo incluído no conteúdo
para impedir a reprodução ou distribuição não autorizada do conteúdo.
</p>
<p>
9. RESTRIÇÕES DE IDADE
Ao usar os sites da Web você confirma que você tem 18 anos de idade ou mais, ou que se você for
menor de 18 anos, você confirma que você está acompanhado e diretamente supervisionado por um
pai ou tutor. Se você for menor de 18 anos, não acesse os sites da Web sem a supervisão direta de seu
pai ou tutor. Você concorda que, se o seu computador, dispositivo habilitado para a Internet, conexão
e/ou instalações de Internet (seja de sua propriedade, arrendado ou emprestado) possa acessar ou
ajudar usuários a acessar os sites ou serviços na Web, você não permitirá ou ajudará, consciente ou
inconscientemente, crianças menores de 18 anos a acessar os sites ou serviços da Web, exceto sob
supervisão direta do pai ou tutor. Você concorda que se permitir ou ajudar menores de 18 anos a acessar
</p>
<p>
o nosso produto sem um pai ou tutor que os supervisione com seu computador, dispositivo habilitado para
a Internet, conexão e/ou instalações de Internet (sejam de sua propriedade, arrendada ou emprestada),
que você assumirá total responsabilidade por qualquer consequência, e que sob nenhuma circunstância
(incluindo, mas não se limitando a negligência), nem a Invento Novo, nem qualquer terceiro provedor de
conteúdo nem seus respectivos agentes serão responsáveis por qualquer dano direto, indireto, incidental,
especial ou consequente decorrente do uso ou inabilidade para usar os sites por usuários menores de 18
anos de idade, mesmo se tal parte tiver sido aconselhada sobre a possibilidade de tais danos.
</p>
<p>
10. DIREITOS DE PROPRIEDADE
Direitos de propriedade intelectual sobre os produtos da Invento Novo:
</p>
<p>
Nós somos os detentores dos direitos de propriedade intelectual sobre o design e as informações dos
sites da Web, incluindo os nomes dos sites da Web e a aparência de nossas combinações de cores,
formatos de botão, e outros elementos gráficos dos sites da Web. Esta propriedade intelectual é protegida
por tratados internacionais, e pelas leis de direitos autorais, marcas registradas, patentes, e segredos
comerciais e outros direitos de propriedade. Por exemplo, nós detemos os direitos autorais sobre a
seleção, organização, arranjo, e aperfeiçoamento dos sites da Web, e também sobre nosso conteúdo
original nos sites da Web.
</p>
<p>
Direitos de propriedade intelectual sobre redes sociais e produtos:
</p>
<p>
A empresa Invento Novo detêm os direitos de propriedade intelectual sobre seus e é detentora dos
direitos autorais conhecidos por nós.
</p>
<p>
11. AÇÕES LEGAIS POR INFRAÇÃO DE DIREITOS DE PROPRIEDADE INTELECTUAL
Se, em sua visão, qualquer direito autoral ou outro direito de propriedade intelectual ("direito de IP") que
você possa ter esteja sendo infringido por/nestes sites na Web, nos informe imediatamente, fornecendo
os seguintes itens:
</p>
1. a assinatura eletrônica ou física do detentor do direito de IP ou a pessoa autorizada a agir em seu
nome;
<p>
2. uma descrição do direito de IP que você afirma ter sido infringido e uma descrição da atividade
infratora;
</p>
<p>
3. a identificação do local onde está o original ou uma cópia autorizada do trabalho registrado (por
exemplo, o URL dos sites da Web onde ele está publicado ou o nome do livro no qual foi publicado ou, no
caso de uma marca registrada, um trecho desse registro comprovando o fato);
</p>
<p>
4. uma cópia da licença que concede a você o direito de usar e proteger tal direito de IP (se você não for
o proprietário do direito de IP);
</p>
<p>
5. a identificação do URL ou outro local específico nesse site onde o material que você afirma ser infrator
fica situado; essas informações devem ser específicas o suficiente para nos permitir localizar tal material;
</p>
<p>
6. seu nome e todos os detalhes de contato; e
</p>
<p>
7. uma declaração sua afirmando que você tem a convicção de boa fé de que o uso em questão não foi
autorizado pelo detentor dos direitos autorais, seu agente, ou pela lei.
</p>
<p>
12. PROVEDORES DE SERVIÇOS DE PAGAMENTO TERCEIRIZADOS
</p>
<p>
A Invento Novo está habilitada a contratar provedores de serviços de pagamento terceirizados ("PSP")
que oferecem serviços de pagamento de transações à Invento Novo e aos usuários dos sites da Web,
para facilitar a venda de produtos ou serviços através dos sites da Web, itens virtuais (por exemplo, uma
assinatura mensal de um produto) ou uma assinatura para baixar um produto. Se você comprar algo dos
sites da Web, você assume, com a PSP relevante, o compromisso de fazer o pagamento (confira isso na
tela de pagamentos).
</p>
<p>
Através de um PSP. Se o acordo foi estabelecido entre você e um PSP, a Invento Novo nunca será
responsável pelas comunicações entre o usuário e o PSP, e qualquer informação que o usuário forneça
ao PSP estará sujeita exclusivamente às políticas de privacidade e/ou a outras regras do PSP. Você
indenizará a Invento Novo por quaisquer devoluções de pagamentos ou outras reivindicações do PSP
resultantes de não cumprimento dos pagamentos.
</p>
<p>
Através da Invento Novo todas as informações recebidas de você no contexto da realização de
pagamentos e do fornecimento de serviços está sujeita à política de privacidade da Invento Novo. Você
pode conferir nossa política de privacidade. Você assume o compromisso de pagar todas as taxas
aplicáveis e os custos associados a sua compra.
</p>
<p>
A Invento Novo não faz reembolsos de maneira alguma. Você não receberá qualquer reembolso ou
compensação por itens virtuais não utilizados. Se você cancelar ou encerrar a sua conta (voluntária ou
involuntariamente), sua conta será descartada e você não receberá qualquer compensação da Invento
Novo.
</p>
<p>
13. SITES DE TERCEIROS E ANUNCIANTES
Os sites da Web pode incluir links para sites da Web de terceiros, inclusive links fornecidos como
resultado de buscas automatizadas. Alguns destes sites podem conter materiais que são censuráveis,
ilegais ou incorretos. Estes links não significam que nós endossamos estes sites ou serviços de terceiros.
Você reconhece e concorda que nós não somos responsáveis por qualquer conteúdo ou outro material
nestes sites de terceiros. Qualquer relação que você tenha com anunciantes encontrados nos sites da
Web ocorre entre você e o anunciante, e você reconhece e concorda que nós não somos responsáveis
por qualquer perda ou reivindicação que você possa ter contra um anunciante.
</p>
<p>
14. USO DE SOFTWARE
Nós podemos disponibilizar software para você transferir ou usar. Este software estará sujeito
às condições do acordo de licenciamento que o acompanha. Se não houver nenhum acordo de
licenciamento apresentado a você com o software, então a seguinte licença, além dos demais termos
destes Termos de uso, governarão o uso deste software. Nós concedemos a você uma licença pessoal,
não exclusiva, intransferível e limitada para instalar o software em qualquer computador individual.
O software é protegido por direitos autorais e outras leis e tratados de propriedade intelectual, e é
propriedade nossa ou de nossos fornecedores. Você não pode vender ou redistribuir o software. Você
não pode incorporar o software ou qualquer parte dele a outro produto. Você não pode fazer engenharia
reversa, descompilar ou desmontar o software, nem tentar derivar seu código-fonte (exceto onde
expressamente permitido por lei). Você não pode modificar, adaptar ou criar trabalhos derivados do
software qualquer que seja a forma, nem remover os avisos proprietários do software. Você concorda em
cumprir todas as leis e regulamentos relativos a seu uso do software. Você não pode autorizar ou ajudar
nenhum terceiro a fazer quaisquer das coisas proibidas neste parágrafo.
</p>
<p>
Nós podemos verificar automaticamente sua versão do software e podemos atualizá-la para melhorar seu
desempenho e recursos. Se você encerrar o software durante uma atualização automática ou, de outra
forma, interferir com a instalação da atualização, o software pode ser danificado e/ou deixar de operar.
</p>
<p>
Você concorda em cumprir totalmente todas as leis de importação e exportação, regulamentos, regras
e ordens dos Países ou de qualquer outra agência governamental ou autoridade estrangeira (por
exemplo, os EUA), e que você não vai, direta ou indiretamente, exportar, reexportar, transferir e/ou lançar
o software, tecnologia relacionada a ele, ou qualquer produto dele para qualquer uso final prescrito,
ou a qualquer país, entidade ou pessoa prescrita (onde quer que esteja), sem a devida autorização
governamental. Você tem total responsabilidade por todas as despesas relativas ao seu cumprimento
das leis, regulamentos, regras e ordens descritos, assumindo-as, e por obter todas as autorizações e
liberações necessárias. Você também concorda em assumir total responsabilidade por todas as despesas
relativas ao seu cumprimento de leis, regulamentos, regras e ordens descritos, e por obter todas as
autorizações e liberações necessárias.
</p>
<p>
15. ISENÇÃO DE GARANTIAS
Nós disponibilizamos os sites da Web no estado em que se encontram, com todas as falhas e conforme
disponível. Nós e nossos fornecedores não oferecemos nenhuma garantia ou obrigações expressas sobre
os sites da Web. A Invento Novo não é obrigada a dar qualquer tipo de suporte. Até a extensão permitida
por lei, nós e nossos fornecedores nos isentamos das garantias presumidas de que os sites da Web e
todo o software, conteúdo e serviços distribuídos pelos sites da Web sejam negociáveis, de qualidade
satisfatória, precisos, oportunos, próprios para um propósito ou finalidade em particular, e não infratores.
Não garantimos que os sites da Web atenderão suas exigências ou estarão livres de erros, seguros, sem
interrupção ou disponíveis o tempo todo. Não garantimos que os resultados que possam ser obtidos com
o uso dos sites da Web (incluindo qualquer serviço de suporte) serão eficientes, seguros ou precisos ou
que satisfarão suas exigências. Não garantimos que você possa acessar ou usar os sites da Web (seja
diretamente ou por redes de terceiros) nos momentos ou locais de sua escolha. Nenhuma informação ou
conselho oral ou por escrito dado por um representante da Spil constituirá uma garantia. Poderá haver
outros direitos de consumidor de acordo com os temos de suas leis territoriais, que este contrato não
poderá mudar.
</p>
<p>
16. LIMITAÇÃO DE RESPONSABILIDADE
Sua única e exclusiva alternativa para qualquer disputa conosco será descontinuar seu uso dos sites
da Web. Sob nenhuma circunstância nossa responsabilidade (ou a responsabilidade de nossa empresa
mãe e nossos fornecedores) por toda e qualquer reivindicação relativa ao uso dos sites da Web deverá
exceder o total de honorários que você nos pagou durante o período pago pelo serviço específico
em questão. Nós, nossa empresa mãe, nossos fornecedores e parceiros de conteúdo não seremos
responsáveis por qualquer dano indireto, especial, incidental, consequente ou exemplar decorrentes
de seu uso do produto, de sua incapacidade de usá-los ou de dependência neles. Essas isenções se
aplicam a qualquer reivindicação por lucros cessantes, perda de dados, perda de garantia, interrupção
no trabalho, falha ou defeito do computador, ou quaisquer outros danos ou perdas comerciais, mesmo
se soubéssemos ou se devêssemos ter conhecimento da possibilidade de tais danos. Como alguns
países, estados ou jurisdições não permitem a isenção ou a limitação de responsabilidade por danos
consequentes ou incidentais, nestes países, estados ou jurisdições, nossa responsabilidade (e a
responsabilidade de nossa matriz e nossos fornecedores) será limitado à extensão permitida por lei.
</p>
<p>
17. INDENIZAÇÃO
Mediante nossa solicitação, você concorda em defender, indenizar, e considerar inocentes nós e
nossa empresa mãe e outras empresas afiliadas, e nossos respectivos empregados, subcontratados,
executivos, diretores e agentes de todas as responsabilidades, reivindicações, e despesas, incluindo
honorários advocatícios, decorrentes de seu uso ou abuso dos sites da Web. Nós nos reservamos o
direito de, às nossas próprias custas, assumir a defesa e o controle exclusivo de qualquer questão sujeita
a indenização por você, caso no qual você cooperará conosco apoiando qualquer defesa disponível.
</p>
<p>
18. USO INTERNACIONAL

Não fazemos nenhuma afirmação de que qualquer conteúdo dos sites da Web é apropriado ou disponível
para uso em locais fora dos Países Baixos. É proibido acessar os sites da Web em territórios onde o
conteúdo for ilegal. Se você optar por acessar os sites da Web em um local fora dos Países Baixos, você
o faz por sua própria iniciativa e você é responsável por cumprir a legislação local.
</p>
<p>
19. ESCOLHA DA LEGISLAÇÃO E DO FORO PARA SOLUCIONAR DISPUTAS
Você concorda que as leis do Brasil governam este contrato e que qualquer reivindicação ou disputa que
você possa ter contra nós, sem levar em conta as regras brasileiras sobre conflito legal e a Convenção
das Nações Unidas sobre Contratos de Venda Internacional de Bens, não terá nenhuma aplicabilidade.
Você também concorda que quaisquer disputas ou reivindicações que você possa ter contra nós serão
solucionadas por um tribunal localizado no Brasil, e você concorda e se submete ao exercício da
jurisdição pessoal deste tribunal com a finalidade de litigar qualquer reivindicação ou ação.
</p>
<p>
Observe que, ao aceitar estes termos de uso, você está:
</p>
<p>
1) Renunciando a reivindicações que poderia ter contra nós baseadas nas leis de outras jurisdições,
incluindo a sua própria;
</p>
<p>
2) Irrevogavelmente consentindo com a jurisdição exclusiva dos tribunais do Brasil e lá localizados sobre
quaisquer disputas ou reivindicações que você tenha contra nós; e
</p>
<p>
3) Submetendo-se à jurisdição pessoal dos tribunais localizados no Brasil com a finalidade de solucionar
quaisquer destas disputas ou reivindicações.
</p>
<p>
20. SEPARAÇÃO E INTEGRAÇÃO.
Este contrato e qualquer termo, política, regra e diretriz suplementar publicada nos sites da Web
constituem o acordo inteiro entre você e nós, e substituem todos os acordos anteriores, orais ou
por escrito. Se qualquer parcela destes termos de uso for considerada inválida ou não passível de
cumprimento, esta parcela será interpretada de forma consistente com a legislação em vigor para refletir,
da forma mais fiel possível, as intenções originais das partes, e as parcelas restantes permanecerão em
vigor e efeito por completo.
</p>
<p>
21. RESCISÃO
Seu direito de usar os sites da Web será automaticamente rescindido se você violar estes termos de uso
ou quaisquer regras ou diretrizes publicadas com relação aos sites da Web. Nós também nos reservamos
o direito, a nosso exclusivo critério, de rescindir seu acesso a todo ou parte dos sites da web, por
qualquer razão, com ou sem notificação.
</p>
</div>
<div id="botoes">
<form method="post" name="form1" id="form1" action="/conta/salvartermos">
<input type="checkbox" id="checkTermos"  /> <label for="checkTermos">Aceito os termos de uso</label> <input type="submit" value="ok" />
</form>
</div>

<script>

window.onload = function () { 
  /*document.getElementById('caixatexto').onscroll = function () { 
  	
	var checkbox = document.getElementById('checkTermos');
	
    var doc = document.getElementById('caixatexto'),
    scrollPosition = doc.scrollTop,
    pageSize = (doc.scrollHeight - doc.clientHeight),
    percentageScrolled = Math.floor((scrollPosition / pageSize) * 100); 

     if (percentageScrolled >= 100){ // if the percentage is >= 50, scroll to top
			
			checkbox.disabled = false;
			
     } 
   }; */
   
   
};

 $(document).ready(function(){
	
   $("#form1").submit(function () {
	   
	 
	   
	   if(document.getElementById('checkTermos').checked == false)
	   {
		   alert('Você tem que concordar com os termos de uso para prosseguir.');
		   return false;
	   }else
	   {
		   alert('Obrigado por concordar com os termos de uso, seja bem vindo ao Glove Brasil.');
		   return true;
	   }
   });

	 
 });

</script>


</body>
</html>