<form action="/admin/baixa/baixar" method="post">
<table width="100%">
<tr>
<td align="right">Cód. Cidade </td>
<td></td>
<td><input type="text" name="cidade" readonly="readonly" value="<?=$this->id_cidade?>"/></td>
</tr>

<tr>
<td align="right">Cód. Franquia </td>
<td></td>
<td><input type="text" name="franquia" readonly="readonly" value="<?=$this->id_franqueado?>"/></td>
</tr>

<tr>
<td align="right">URL no apontador </td>
<td></td>
<td> <input name="apontador_url" type="text" size="150" value="<?=$this->url?>"/></td>
</tr>

<tr>
<td></td>
<td></td>
<td><input type="submit" value="Iniciar" /></td>
</tr>

</table>
</form>

