
<div id="content-table-inner">  Total de registros encontrados: <b><?=$this->total_registros?></b>
    <table border="0" cellpadding="0" cellspacing="0" id="paging-table" width="">
              <tr>
                <td align="center">
              
                <a href="javascript:void(0);" onclick="javascript:grid(1);" class="page-far-left"></a> <a href="javascript:void(0);" onclick="javascript:grid('<?=$this->anterior?>');" class="page-left"></a>
                  <div id="page-info">Página <strong><?=$this->pagina?></strong> / <?=$this->total_paginas?></div>
                  <a href="javascript:void(0);" onclick="javascript:grid('<?=$this->proxima?>');" class="page-right"></a> <a href="javascript:void(0);" onclick="javascript:grid('<?=$this->ultima?>');" class="page-far-right"></a></td>
              </tr>
      </table>
  <div class="clear"></div>
</div>

<form id="mainform" action="">
  <table width="100%" border="0" align="right" cellpadding="0" cellspacing="0" id="product-table">
	          <tr>
	            <th width="3%" class="table-header-check"><a id="toggle-all" ></a></th>
	            <th width="19%" class="table-header-options line-left"><a>Id</a></th>                
	            <th width="61%" class="table-header-repeat line-left minwidth-1"><a>Cidade</a></th>
                 <th width="61%" class="table-header-repeat line-left minwidth-1"><a>Slug</a></th>
	            <th width="61%" class="table-header-repeat line-left minwidth-1"><a>Estado</a></th>                <th width="17%" class="table-header-options line-left"><a href="">Acoes</a></th>
              </tr>
              
            <?php
			if($this->total_registros > 0)
			{
				
			
	        foreach ($this->lista as $chave => $valor){
	        ?>
	          <tr>
	            <td><input  type="checkbox" name="exclui[<?=$valor->ID_CIDADE?>]" id="exclui[<?=$valor->ID_CIDADE?>]"/></td>
                <td><?=$valor->ID_CIDADE?></td>
	            <td><?=utf8_encode($valor->NOME_CIDADE)?></td>
	            <td><?=$valor->SLUG_CIDADE?></td>                
				<td align="center"><?=$valor->NOME_PAIS_pais?> - <?=$valor->SGL_ESTADO_uf?></td>                
                	<td class="options-width">
	            	<a href="javascript:void(0);" onclick="window.location='/<?=$this->modulo?>/<?=$this->controlador?>/editar/id/<?=$valor->ID_CIDADE?>'" title="Editar" class="icon-1 info-tooltip"></a>
                  	<a href="javascript:deletar('<?=$valor->ID_CIDADE?>');" title="Excluir" class="icon-2 info-tooltip"></a>
                                      
                    
	            </td>	            
              </tr>
	          
              <?php }
			  
			}else{?>
            
            <tr>
	            <td colspan="5" align="center">Nenhum registro cadastrado.</td>	            
            </tr>
            
            <?php } ?>
              
	          

            </table>
	        
          </form>

	      
 <div id="content-table-inner">
    <table border="0" cellpadding="0" cellspacing="0" id="paging-table" width="">
               <tr>
                <td align="center">
                <a href="javascript:void(0);" onclick="javascript:grid(1);" class="page-far-left"></a> <a href="javascript:void(0);" onclick="javascript:grid('<?=$this->anterior?>');" class="page-left"></a>
                  <div id="page-info">Página <strong><?=$this->pagina?></strong> / <?=$this->total_paginas?></div>
                  <a href="javascript:void(0);" onclick="javascript:grid('<?=$this->proxima?>');" class="page-right"></a> <a href="javascript:void(0);" onclick="javascript:grid('<?=$this->ultima?>');" class="page-far-right"></a></td>
              </tr>
      </table>
  <div class="clear"></div>
</div>