<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Glove Brasil</title>
	<meta name="description" content="">
	<meta name="author" content="">
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

	<!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="/assets/portal/login/css/base.css">
	<link rel="stylesheet" href="/assets/portal/login/css/skeleton.css">
	<link rel="stylesheet" href="/assets/portal/login/css/screen.css">
    <link rel="stylesheet" href="/assets/portal/login/css/mediaelementplayer.css" />
    <!--[if IE 7]>
        <link rel="stylesheet" href="stylesheets/ie7.css">
    <![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="/assets/portal/login/images/favicon.ico">
	<link rel="apple-touch-icon" href="/assets/portal/login/images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/assets/portal/login/images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/assets/portal/login/images/apple-touch-icon-114x114.png">
    
    <!-- Fonts
	================================================== -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic,300,300italic' rel='stylesheet' type='text/css'>
    
    <!-- Scripts
	================================================== -->
    <script src="/assets/portal/login/js/jquery-1.7.min.js" type="text/javascript"></script>
    <script src="/assets/portal/login/js/jquery.easing.1.3.js" type="text/javascript"></script>
    <script src="/assets/portal/login/js/jquery.animate-colors-min.js" type="text/javascript"></script>
    <!--/***********************************************
    * Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
    * This notice MUST stay intact for legal use
    * Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
    ***********************************************/-->
   <script src="/assets/portal/login/js/ddsmoothmenu.js" type="text/javascript"></script>
    <script src="/assets/portal/login/js/jquery.cssAnimate.mini.js" type="text/javascript"></script>
    <script src="/assets/portal/login/js/jquery.fitvids.js" type="text/javascript"></script>
    <script src="/assets/portal/login/js/jquery.flexslider-min.js" type="text/javascript"></script>
	<script src="/assets/portal/login/js/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script src="/assets/portal/login/js/mediaelement-and-player.min.js"></script>
    <script src="/assets/portal/login/js/screen.js" type="text/javascript"></script>
    
	
	
	
    
    <link rel="stylesheet" type="text/css" href="/assets/toastmessage/jquery.toastmessage.css"/>
	<script type="text/javascript" src="/assets/toastmessage/jquery.toastmessage.js"></script>
    
	<script type="text/javascript" src="/assets/fancybox2/jquery.fancybox.js?v=2.0.6"></script>
	<link rel="stylesheet" type="text/css" href="/assets/fancybox2/jquery.fancybox.css?v=2.0.6" media="screen" />
  	   <script src="/assets/core.js"></script>
    <style>
	#likeBox
	{
		z-index:10000000000000000000;
		position: fixed;
		width: 240px;
		height: 234px;
		right: 0;
		bottom: 0;
		padding: 1px;
		margin: auto auto auto auto;
		-moz-box-shadow: 1px 1px 1px rgba(0,0,0,0.1);
		box-shadow: 1px 1px 1px rgba(0,0,0,0.1);
		-webkit-box-shadow: 1px 1px 1px rgba(0,0,0,0.1);
		border-radius: 3px;
		-moz-border-radius: 3px;
		-webkit-border-radius: 3px;
	}

	</style>
    
</head>

<body>



              <div id="likeBox">
<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FGlove-Brasil%2F286336624832723%3Ffref%3Dts&amp;width=240&amp;height=255&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;border_color&amp;header=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:240px; height:234px; background-color:#FFF;" allowTransparency="true"></iframe>
           </div> 

	<!-- Site Backgrounds
	================================================== -->
	
    <!-- Change to class="poswrapheaderline wide" and class="headerline full" for a full-width header line -->
	<div class="poswrapheaderline"><div class="headerline"></div></div>  
    <!-- Remove or uncomment depending on if you want a background image or tile -->
    <div class="tiledbackground"></div>
    <!--img src="images/bg.jpg" alt="" id="background" /-->
    <!-- Change to class="poswrapper wide" and class="whitebackground full" for a full-width site background -->
    <div class="poswrapper"><div class="whitebackground"></div></div>

	<div class="container main portfolio4column">
    
        <!-- Header | Logo, Menu
		================================================== -->
	
		<div class="sixteen columns header">
        
			<a href="/" class="logohover"><div class="logo"></div></a>
            <div class="mainmenu" >
                <div id="mainmenu" class="ddsmoothmenu" style="height:50px;">
                	<form action="/conta/logar" name="formLogin" id="formLogin" method="post">
                    <ul>
                        <li style="margin-right:10px; margin-top:22px;">
                       <label for="EMAIL" style="margin-bottom:5px; margin-top:10px; padding:5px; color:#FFFFFF;">Seu e-mail</label>
                       <input name="EMAIL" type="text" id="EMAIL"  />
                    
                        </li>
                        <li style="margin-right:10px; margin-top:22px;">
					    <label for="SENHA" style="margin-bottom:5px; margin-top:10px;padding:5px;  color:#FFFFFF;">Senha</label>                        
                        <input name="SENHA" type="password" id="SENHA" />
                      
                        </li>
                        <li style="margin-left:0px; padding-top:44px;">
                        <label for="SENHA" style="margin-bottom:3px; margin-top:0px;padding:0px;"></label>          
                        <input type="submit" value="Entrar">
                        v 1.1 beta</li> 
                    </ul>
                    </form>
                    <br style="clear: left" />
                </div>
                
                <!-- Responsive Menu -->
                
				<form id="responsive-menu" action="#" method="post">
                    <select>
                        <option value="">Navigation</option>
                    </select>
				</form>
				
            </div>
		</div>
        
        <!-- Page Title And Social
		================================================== -->
        
		<div class="pagetitle">
        <div style="float:right; padding-bottom:15px; overflow:hidden; margin-right:50px;">
	      <a href="/conta" title="Criar uma conta no Glove Brasil" rel="normal_request">Ainda não tenho cadastro</a> | 
          <a href="javascript:void(0);" onclick="Popup('/conta/precuperarsenha', 350, 200);" title="Esqueci minha senha!">Esqueci minha senha</a>
        </div>
        	<div class="pagetitleholder">
        	  <h1 style="font-size:20px;"> Relacionamento, amizade e diversão.<br>
Amplie seus horizontes, faça parte do Glove Brasil. </h1>
             
            </div>
            <div class="socialholder">
            	<ul class="socialicons">
                	<li><a href="https://www.facebook.com/pages/Glove-Brasil/286336624832723?fref=ts" rel="normal_request" target="_blank" class="social_facebook"></a><div>Facebook</div></li>
                    <li><a href="#" target="_blank" class="social_twitter"></a><div>Twitter</div></li>
                    <!--<li><a href="#" class="social_googleplus"></a><div>GooglePlus</div></li>-->
                    <!--<li><a href="#" class="social_vimeo"></a><div>Vimeo</div></li>
                    <li><a href="#" class="social_rss"></a><div>RSS Feed</div></li>
                    <li><a href="#" class="social_linkedin"></a><div>LinkedIn</div></li>
                    <li><a href="#" class="social_flickr"></a><div>Flickr</div></li>-->
                    <!--<li><a href="#" class="social_youtube"></a><div>Youtube</div></li>-->
                    <!--<li><a href="#" class="social_pinterest"></a><div>Pinterest</div></li>
                    -->
                </ul>
			</div>
            <!--div class="pagetitlebackground"></div-->
        </div>
		
        <!-- Slider
		================================================== -->
        
		<div class="homeslider row">        
            <div class="flexslider clearfix">
                <ul class="slides">
                    <li><img src="/assets/portal/login/images/banner/banner1.jpg" alt="" /><!--<div class="flex-caption"><strong>An HTML 5 Valid Template.</strong> You can also grab the WordPress Version here!</div>--></li>
                    <li><img src="/assets/portal/login/images/banner/banner2.jpg" alt="" /></li>
                  
                </ul>
            </div>
            <div class="sliderspacefix"></div>
		</div>

        <!-- Text Block
		================================================== -->
        
		<div class="sixteen columns row textblock">

            <div class="one_fourth">
                <h5 class="teaserheadline"><img src="/assets/portal/login/images/icons/down.png" alt="" />Glove Brasil</h5>
                <p>
Uma rede social inteiramente 
voltada para o público
homossexual, não homofóbica,
livre de preconceitos e com
amplo alcance de usuários.<br/><br/><br/><a href="/conta" rel="normal_request" class="button">Faça parte</a></p>
            </div>
            <div class="one_fourth">
                <h5 class="teaserheadline"><img src="/assets/portal/login/images/icons/cog.png" alt="" />Liberdade</h5>
                <p>Especialmente desenvolvido para 
que nossos usuários expressem
livremente suas idéias,
compartilhem pensamentos e
ampliem seus horizontes.<br/><br/><a href="/conta" rel="normal_request" class="button">Experimente</a></p>
            </div>
            <div class="one_fourth">
                <h5 class="teaserheadline"><img src="/assets/portal/login/images/icons/help.png" alt="" />Bate Papo</h5>
                <p> Troque mensagens instantâneas online (em tempo real)   com velhos e novos amigos  , faça do Glove Brasil sua nova rede social. <br/><br/><br/><a href="/conta" class="button" rel="normal_request">Conheça</a></p>
            </div>
            <div class="one_fourth lastcolumn">
                 <h5 class="teaserheadline"><img src="/assets/portal/login/images/icons/planet.png" alt=""  />Relacionamento</h5>
                <p>Encontre o que você busca.
Um ambiente seguro e não 
homofóbico em que todos 
compartilham de um mesmo 
propósito.<br/><br/><br/><a href="/conta" class="button" rel="normal_request">Compartilhe</a></p>
			</div>
            
            <div class="clear"></div>
        </div>
        
       
		
      <!-- Bottom Padding Adjust
       ================================================== --> 
       <div class="sixteen columns bottomadjust"></div>
            
	</div><!-- container -->

	<!-- Footer
	================================================== -->
	
    <!-- Change to class="container footerwrap full" for a full-width footer -->
	<!-- container -->
    
    <!-- Sub-Footer
	================================================== -->
    
            
    
    <!-- Change to class="container subfooterwrap full" for a full-width subfooter -->
    <div class="container subfooterwrap">
    
    	<div class="footeropen"></div>
    
    	<div class="subfooter">
        	<div class="eight columns siteinfo">@ COPYRIGHT  2012-<?=date("Y")?>, <a href= "http://www.inventonovo.com.br" target="_blank" >INVENTO NOVO - TALENTOS E IDEIAS</a></div>
                <div style="float:right;"><!--<a href="#">Fale Conosco</a>--></div>
            </div>
        </div>
    </div>

<!-- End Document
================================================== -->
</body>
</html>