<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  dir="ltr">
<head>	
<title>Glove Brasil Atividades</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="description" content="<?=$this->msg?>" />
<!-- Facebook Meta Tags -->
<meta property="og:title" content="Glove Brasil Atividades"/>
<meta property="og:image" content="http://www.glovebrasil.com.br/assets/portal/login/images/logog.jpg"/>
<meta property="og:site_name" content="Glove Brasil"/>
<meta property="og:description" content="<?=$this->msg?>" />
</head>
<body>

<p>Glove Brasil</p>

<?php if($this->logado == true){ ?>
<p>Abrindo post...</p>
<script>
window.location = '/meuperfil-<?=$this->usuario->ID_USUARIO?>/post/<?=$this->cod?>';
</script>

<?php
}else
{
?>

<p>É necessário efetuar o login do <b>Glove Brasil</b> para visualizar este post, aguarde você será redirecionado para a tela de login...</p>

<script>
var t=setTimeout(function(){ window.location = '/'; },5000)
</script>

<?php
}
?>

</body>
</html>