    <?php
	
		
		/*CKEditor*/
		$this->headScript()->appendFile($this->baseUrl() . '/assets/admin/ckeditor/ckeditor.js');
   

		$this->headScript()->appendFile("/assets/admin/jstree_pre1.0_fix_1/_lib/jquery.cookie.js");
		$this->headScript()->appendFile("/assets/admin/jstree_pre1.0_fix_1/_lib/jquery.hotkeys.js");
		$this->headScript()->appendFile("/assets/admin/jstree_pre1.0_fix_1/jquery.jstree.js");
		$this->headLink()->appendStylesheet('/path/to/page-styles.css');
		$this->headScript()->appendFile("/assets/admin/jstree_pre1.0_fix_1/_docs/syntax/!script.js");		
		
		
		$this->headLink()->appendStylesheet($this->baseUrl() . '/assets/uploadify-v2.1.4/uploadify.css');
		$this->headScript()->appendFile($this->baseUrl() . '/assets/uploadify-v2.1.4/swfobject.js');
		$this->headScript()->appendFile($this->baseUrl() . '/assets/uploadify-v2.1.4/jquery.uploadify.v2.1.4.js');
	?>
    
<?php $this->placeholder('multiscripts')->captureStart();?>

	<style>
	input
	{
		color:#333;
		border: 1px solid #999;
		background-color:#E5E5E5;
		padding:5px;
		margin-left:3px;
	}
	</style>
    
    
<?php $this->placeholder('multiscripts')->captureEnd() ?>
    
<div id="page-heading">
	<h1><img src="/assets/admin/icones/icon1.png"> Gerenciar menus e páginas do site</h1>
</div>


    
<table width="100%" border="0" cellpadding="0" align="center">
    <tr>
   	  <td height="70" colspan="3" valign="top" id="mmenu">

        <input type="button"  id="add_folder" value="Novo menu" style="display:block; float:left;"/>
        <!--<input type="button" id="add_default" value="add arquivo" style="display:block; float:left;"/> -->
        <input type="button" id="rename" value="Renomear" style="display:block; float:left;"/>
        <input type="button" id="remove" value="Excluir" style="display:block; float:left;"/>
        <input type="button" id="cut" value="recortar" style="display:block; float:left;"/>
        <input type="button" id="copy" value="copiar" style="display:block; float:left;"/>
        <input type="button" id="paste" value="colar" style="display:block; float:left;"/>
        <!--<input type="button"  value="reconstruir" onclick="$.get('/admin/categorias/index?reconstruct', function () { $('#demo').jstree('refresh',-1); });"   />
        <input type="button"  id="analyze" value="analizar" onclick="$('#alog').load('/admin/categorias/index?analyze');" />
        <input type="button"  value="recarregar" onclick="$('#demo').jstree('refresh',-1);" />
         <input name="lixo" type="button" id="fechar"   value="Fechar todos" />
        <br />
        <input type="text" id="text" value="" style="display:block; float:left;" />
        <input type="button" id="search" value="buscar" style="display:block; float:left;"/>
        <input type="button" id="clear_search" value="limpar" style="display:block; float:left;"/>
        -->
       
      </td>
  </tr>
    <tr>
    	<td width="40%" valign="top">
        <div id="description">

<!-- the tree container (notice NOT an UL node) -->

<div id="demo" class="demo" style="height:600px;width:300px; border: 5px solid #cccccc; overflow:auto;"></div>





<div id='alog' style="border:1px solid gray; padding:5px; height:100px; margin-top:15px; overflow:auto; display:none; font-family:Monospace;"></div>

<!-- JavaScript neccessary for the tree -->

<script type="text/javascript" class="source below">



$(function () {



$("#demo")

	.bind("before.jstree", function (e, data) {

		$("#alog").append(data.func + "<br />");

	})

	.jstree({ 

		// List of active plugins

		"plugins" : [ 

			"themes","json_data","ui","crrm","cookies","dnd","search","types","hotkeys","contextmenu" /*,"checkbox"*/

		],



		// I usually configure the plugin that handles the data first

		// This example uses JSON as it is most common

		"json_data" : { 

			// This tree is ajax enabled - as this is most common, and maybe a bit more complex

			// All the options are almost the same as jQuery's AJAX (read the docs)

			"ajax" : {

				// the URL to fetch the data

				"url" : "/<?=$this->modulo?>/<?=$this->controlador?>/index",

				// the `data` function is executed in the instance's scope

				// the parameter is the node being loaded 

				// (may be -1, 0, or undefined when loading the root nodes)

				"data" : function (n) { 

					// the result is fed to the AJAX request `data` option

					return { 

						"operation" : "get_children", 

						"id" : n.attr ? n.attr("id").replace("node_","") : 1 

					}; 

				}

			}

		},

		// Configuring the search plugin

		"search" : {

			// As this has been a common question - async search

			// Same as above - the `ajax` config option is actually jQuery's AJAX object

			"ajax" : {

				"url" : "/<?=$this->modulo?>/<?=$this->controlador?>/index",

				// You get the search string as a parameter

				"data" : function (str) {

					return { 

						"operation" : "search", 

						"search_str" : str 

					}; 

				}

			}

		},

		// Using types - most of the time this is an overkill

		// read the docs carefully to decide whether you need types

		"types" : {

			// I set both options to -2, as I do not need depth and children count checking

			// Those two checks may slow jstree a lot, so use only when needed

			"max_depth" : -2,

			"max_children" : -2,

			// I want only `drive` nodes to be root nodes 

			// This will prevent moving or creating any other type as a root node

			"valid_children" : [ "drive" ],

			"types" : {

				// The default type

				"default" : {

					// I want this type to have no children (so only leaf nodes)

					// In my case - those are files

					"valid_children" : "none",

					// If we specify an icon for the default type it WILL OVERRIDE the theme icons

					"icon" : {

						"image" : "/assets/admin/jstree_pre1.0_fix_1/_demo/file.png"

					}

				},

				// The `folder` type

				"folder" : {

					// can have files and other folders inside of it, but NOT `drive` nodes

					"valid_children" : [ "default", "folder" ],

					"icon" : {

						"image" : "/assets/admin/jstree_pre1.0_fix_1/_demo/folder.png"

					}

				},

				// The `drive` nodes 

				"drive" : {

					// can have files and folders inside, but NOT other `drive` nodes

					"valid_children" : [ "default", "folder" ],

					"icon" : {

						"image" : "/assets/admin/jstree_pre1.0_fix_1/_demo/root.png"

					},

					// those prevent the functions with the same name to be used on `drive` nodes

					// internally the `before` event is used

					"start_drag" : false,

					"move_node" : false,

					"delete_node" : false,

					"remove" : false

				}

			}

		},

		// UI & core - the nodes to initially select and open will be overwritten by the cookie plugin



		// the UI plugin - it handles selecting/deselecting/hovering nodes

		"ui" : {

			// this makes the node with ID node_4 selected onload

			"initially_select" : [ "node_4" ]

		},

		// the core plugin - not many options here

		"core" : { 

			// just open those two nodes up

			// as this is an AJAX enabled tree, both will be downloaded from the server

			"initially_open" : [ "node_2" , "node_3" ],
			 strings: { loading: "carregando...", new_node: "Novo" }

		},

		    "themes":
            {
                theme: "apple"
            }

	})

	.bind("create.jstree", function (e, data) {

		$.post(

			"/<?=$this->modulo?>/<?=$this->controlador?>/index", 

			{ 

				"operation" : "create_node", 

				"id" : data.rslt.parent.attr("id").replace("node_",""), 

				"position" : data.rslt.position,

				"title" : data.rslt.name,

				"type" : data.rslt.obj.attr("rel")

			}, 

			function (r) {
			
				if(r.status) {
					
					
					
					$(data.rslt.obj).attr("id", "node_" + r.id);
					
					
					
					$(data.rslt.obj).click(function () {

		                    //carregaDadosEdit(id);
							//alert('ID CRIADO: ' + r.id);
		                   
		                });

				}

				else {

					$.jstree.rollback(data.rlbk);

				}

			}

		);

	})

	.bind("remove.jstree", function (e, data) {

		if(!(confirm("Remover menu?")))
		{
			data.inst.refresh();
			return false;
			
		}else
		{
			
		data.rslt.obj.each(function () {

			$.ajax({

				async : false,

				type: 'POST',

				url: "/<?=$this->modulo?>/<?=$this->controlador?>/index",

				data : { 

					"operation" : "remove_node", 

					"id" : this.id.replace("node_","")

				}, 

				success : function (r) {

					if(!r.status) {

						data.inst.refresh();

					}

				}

			});

		});
	}

	})

	.bind("rename.jstree", function (e, data) {

		$.post(

			"/<?=$this->modulo?>/<?=$this->controlador?>/index", 

			{ 

				"operation" : "rename_node", 

				"id" : data.rslt.obj.attr("id").replace("node_",""),

				"title" : data.rslt.new_name

			}, 

			function (r) {

				if(!r.status) {

					$.jstree.rollback(data.rlbk);

				}

			}

		);

	})

	.bind("move_node.jstree", function (e, data) {

		data.rslt.o.each(function (i) {

			$.ajax({

				async : false,

				type: 'POST',

				url: "/<?=$this->modulo?>/<?=$this->controlador?>/index",

				data : { 

					"operation" : "move_node", 

					"id" : $(this).attr("id").replace("node_",""), 

					"ref" : data.rslt.cr === -1 ? 1 : data.rslt.np.attr("id").replace("node_",""), 

					"position" : data.rslt.cp + i,

					"title" : data.rslt.name,

					"copy" : data.rslt.cy ? 1 : 0

				},

				success : function (r) {

					if(!r.status) {

						$.jstree.rollback(data.rlbk);

					}

					else {

						$(data.rslt.oc).attr("id", "node_" + r.id);

						if(data.rslt.cy && $(data.rslt.oc).children("UL").length) {

							data.inst.refresh(data.inst._get_parent(data.rslt.oc));

						}

					}

					$("#analyze").click();

				}

			});

		});

	}).bind("select_node.jstree", function (e, data) { 
		
		 var id = data.rslt.obj[0].id.replace("node_", "");
		 carregaForm(id);
		 
		 
 				   
		 
		 
		 
		
	});

});

</script>

<script type="text/javascript" class="source below">

// Code for the menu buttons

$(function () { 

	$("#mmenu input").click(function () {

		switch(this.id) {

			case "add_default":

			case "add_folder":
				
				$("#demo").jstree("create", null, "last", { "attr" : { "rel" : this.id.toString().replace("add_", "") } });

				break;

			case "search":

				$("#demo").jstree("search", document.getElementById("text").value);

				break;

			case "text": break;

			default:

				$("#demo").jstree(this.id);

				break;

		}

	});

});

 

  carregaForm = function (id) {

        //se o menu clicado não for o "MENUS DO PORTAL"
        if (id != 2) {
			$.ajax({
                type: 'POST',
                url: "/<?=$this->modulo?>/<?=$this->controlador?>/editar",
				data: {id : id},
                success: function (r) {
					
				   
				   if (CKEDITOR.instances['CONTEUDO']) { CKEDITOR.remove(CKEDITOR.instances['CONTEUDO']); }
				   
				   $("#form").html(r);
				   
 				   
				 
				   
				  
				   
			       
				   
				 
				   editor = CKEDITOR.replace('CONTEUDO');
                   editor.config.width = '530';
                   editor.config.height = '300';
                   editor.config.resize_maxWidth = '300';
                   editor.config.resize_enabled = false;
                   editor.config.autoUpdateElement = true;
                   editor.config.startupFocus = false;
                   editor.config.entities_latin = false;
                   editor.config.entities_greek = false;
                   editor.config.toolbar =
                    [
                        ['Source', 'Preview', 'Bold', 'Italic', 'Underline', 'Link', 'Font', 'FontSize', 'TextColor', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image','Video',   '-', 'Flash', 'YouTube', '-', 'inserthtml', 'PasteText','PasteFromWord', 'Templates', '-', 'fileicon', 'gmap', '-', 'Maximize', 'oEmbed', 'ckeditor_wiris_CAS']
                    ];

                   editor.config.filebrowserWindowFeatures = 'scrollbars=yes';
                   editor.config.ImageBrowserWindowWidth = 500;
                   editor.config.ImageBrowserWindowHeight = 600;
				   
			       editor.config.filebrowserBrowseUrl = '/assets/admin/ckeditor/ckfinder/ckfinder.html',
			       editor.config.filebrowserImageBrowseUrl = '/assets/admin/ckeditor/ckfinder/ckfinder.html?type=Images',
				   editor.config.filebrowserFlashBrowseUrl = '/assets/admin/ckeditor/ckfinder/ckfinder.html?type=Flash',
				   editor.config.filebrowserUploadUrl = '/assets/admin/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&amp;type=Files',
				   editor.config.filebrowserImageUploadUrl = '/assets/admin/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&amp;type=Images',
				   editor.config.filebrowserFlashUploadUrl = '/assets/admin/ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&amp;type=Flash'

                   
                   editor.config.extraPlugins = "youtube,galeria_dingous,dingous_fotos,inserthtml,syntaxhighlight,gmap,fileicon,video"; //,oEmbed,ckeditor_wiris
						
				   
					
				}
			});
		}
  };

</script>

</div>



</div>

        
        
  </td>
      <td width="2%">&nbsp;</td>
        <td width="60%" valign="top">
        
         <div id="form"></div>
     
        
        </td>
    </tr>

</table>

<script>
$(document).ready(function()
{
	//$.post('/admin/categorias/form', function(data) { $('#form').html(data); } );
	
	
	$("#fechar").click(function(){
		
				//$("#demo").jstree('rename_node', 'node_8' , 'teste' );
				//$('#demo').jstree('refresh', 'node_8');
				var aaa = $('#demo').jstree('close_all', -1, true);

		});
});
</script>