<?
$profile = new Zend_Session_Namespace('perfil');
?>

<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php echo $this->headMeta(); ?>

<?php 
	echo $this->headTitle();
?>

<link rel="stylesheet" href="/assets/portal/default/css/default.css" media="screen" />
<link rel="stylesheet" href="/assets/portal/defaultOld/css/estilo.css" media="screen" />
  <!-- jQuery file -->
    
	<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery-1.7.2.min.js"><\/script>')</script>
    -->

	<script src="/assets/portal/default/js/jquery-1.7.2.min.js"></script>

    <link rel="stylesheet" href="/assets/admin/js/jquery-ui-1.8.16.custom/css/redmond/jquery-ui-1.8.16.custom.css"> 	
    <script src="/assets/admin/js/jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.core.js" type="text/javascript"></script>
    <script src="/assets/admin/js/jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="/assets/admin/js/jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.tabs.js" type="text/javascript"></script>

	
        <link rel="stylesheet" type="text/css" href="/assets/toastmessage/jquery.toastmessage.css"/>
	<script type="text/javascript" src="/assets/toastmessage/jquery.toastmessage.js"></script>
    

	<script type="text/javascript" src="/assets/fancybox2/jquery.fancybox.js?v=2.0.6"></script>
	<link rel="stylesheet" type="text/css" href="/assets/fancybox2/jquery.fancybox.css?v=2.0.6" media="screen" />
    
    
     <script src="/assets/core.js"></script>
     
   	<script type="text/javascript" src="/assets/InterfaceUsuario.js"></script> 
	
	<script src="/assets/admin/jquery.alerts-1.1/jquery.alerts.js" type="text/javascript"></script> 
	<link href="/assets/admin/jquery.alerts-1.1/jquery.alerts.css" rel="stylesheet" type="text/css" media="screen" />     

<style>
body
{
	font-family:Verdana, Geneva, sans-serif;
	font-size:11px;
	margin: 0 0 0 0;
}
</style>
   
<?php echo $this->headScript() ?>

<?php echo $this->headStyle() ?>

<?php echo $this->headLink() ?>

 <!--Criado com intuito de adicionar várias referências de js e css-->
<?php echo  $this->placeholder('multiscripts') ?>
    
    
    
</head>

<body>


<div id="main">
  
		<?php echo $this->layout()->content; ?>
    
  
</div>  
 
 <?php echo $this->inlineScript(); ?>
 
</body>
</html>