<?
$profile = new Zend_Session_Namespace('perfil');
?>

<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php echo $this->headMeta(); ?>

<?php 
	echo $this->headTitle();
?>


<script type="text/javascript" src="/assets/portal/defaultOld/scripts/bValidator-0.6/jquery-1.7.2.min.js"></script>

<link rel="stylesheet" href="/assets/admin/js/jquery-ui-1.8.16.custom/css/redmond/jquery-ui-1.8.16.custom.css"> 	
<script src="/assets/admin/js/jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.core.js" type="text/javascript"></script>
<script src="/assets/admin/js/jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.widget.js" type="text/javascript"></script>
<script src="/assets/admin/js/jquery-ui-1.8.16.custom/development-bundle/ui/jquery.ui.tabs.js" type="text/javascript"></script>

<style>
body
{
	font-family:Verdana, Geneva, sans-serif;
	font-size:11px;
	margin: 0 0 0 0;
}
</style>
   
<?php echo $this->headScript() ?>

<?php echo $this->headStyle() ?>

<?php echo $this->headLink() ?>

 <!--Criado com intuito de adicionar várias referências de js e css-->
<?php echo  $this->placeholder('multiscripts') ?>
    
    
    
</head>


<?php echo $this->layout()->content; ?>

<?php echo $this->inlineScript(); ?>
 

</html>