<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/assets/portal/fancybox/jquery.fancybox-1.3.4.css');
$this->headScript()->appendFile("/assets/portal/fancybox/jquery.fancybox-1.3.4.pack.js");		
?>


<style>

.tabelaGrid tr th
{
	padding:8px;
	font-size:12px;
}

.tabelaGrid tr td
{
	padding:3px;
	font-size:12px;
}

body
{
	font-family:Verdana, Geneva, sans-serif;
	
}

</style>



<table width="100%" border="0" cellpadding="0" align="center">
  <tr>
    <td width="49%" valign="top">
    
    <?php if($this->modo == "view"){?>
    
    <input type="button" name="btnVoltar" id="btnVoltar" value="Voltar" onclick="window.location = '/admin/participromocoes/';" />
    <input type="button" name="btnImprimir" id="btnImprimir" value="Versão para impressão" />
    
    <?php }else{ ?>

    <input type="button" name="btnImprimirNow" id="btnImprimirNow" value="Imprimir" onclick="window.print();" />
    <input type="button" name="btnFechar" id="btnFechar" value="Fechar" onclick="window.close();" />

    
    <?php } ?>
    
    </td>
    <td width="22%" valign="top">&nbsp;</td>
    <td width="27%" valign="top">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3" valign="top"><div id="grid"></div></td>
  </tr>
</table>
<br />
<table width="100%" class="tabelaGrid">
<thead>
<tr>
    <th width="7%" bgcolor="#CCCCCC">Código</th>
    <th width="23%" bgcolor="#CCCCCC">Nome do participante</th>
    <th bgcolor="#CCCCCC">E-mail</th>
    <th bgcolor="#CCCCCC">Telefone</th>
    <th bgcolor="#CCCCCC">Cidade</th>
    <th bgcolor="#CCCCCC">Dt. Cadastro</th>
    <?php if($this->modo == "view"){?>
    <th bgcolor="#CCCCCC">Mensagem</th>
    <?php } ?>
    
</tr>

</thead>

<tbody>

<?php 
$i=1;
foreach($this->participantes as $chave => $valor){

$cor = "#FFFFFF";
$cor = $i % 2 == 0 ? "#FFFFFF" : "#F3F3F3";
	
?>

    <tr>
        
        <td align="center" bgcolor="<?=$cor?>"><?=$valor->ID_PARTICIPANTE?></td>
        <td align="center" bgcolor="<?=$cor?>"><?=$valor->NOME?></td>
        <td width="16%" bgcolor="<?=$cor?>" align="center"><?=$valor->EMAIL?></td>
        <td width="10%" bgcolor="<?=$cor?>" align="center"><?=$valor->TELEFONE?></td>
        <td width="11%" bgcolor="<?=$cor?>"align="center"><?=$valor->CIDADE?></td>
        <td width="11%" bgcolor="<?=$cor?>"align="center"><?=Lumine_Util::FormatDateTime($valor->DT_CADASTRO, "%d/%m/%Y %H:%M")?></td>    
        <?php if($this->modo == "view"){?>
        <td width="22%" bgcolor="<?=$cor?>" align="center"><?=$valor->MENSAGEM?></td>
        <?php } ?>
    
    </tr>
    
<?php  $i++;} ?>

</tbody>

</table>


<script>


$(document).ready(function () {
	
		$("#btnImprimir").click(function(e, v){
				
				AbreJanela('/admin/participromocoes/visualizaparticipantes/id/<?=$this->id?>/mod/print', 1024, 600);
				
			});			
	
});

</script>
