<div id="page-heading">
	<h1><img src="/assets/admin/icones/icon1.png"> Controladores não cadastrados nos módulos</h1>
</div>


    
<table width="100%" border="0" cellpadding="0" align="center">
    <tr>
    	<td width="49%" valign="top">&nbsp;</td>
    	<td width="22%" valign="top">&nbsp;</td>
    	<td width="27%" valign="top">&nbsp;</td>
    </tr>
    <tr>
    	<td colspan="3" valign="top">
   	    	
            
            <br /><br />
            
            <form id="mainform" action="">
  <table width="100%" border="0" align="right" cellpadding="0" cellspacing="0" id="product-table">
	          <tr>

	            <th width="61%" class="table-header-repeat line-left minwidth-1"><a href="">Controlador</a></th>
                <th width="17%" class="table-header-options line-left"><a href="">Acoes</a></th>
                
              </tr>
              
            <?php
			if($this->dif > 0)
			{
	        foreach ($this->dif as $chave => $valor){
	        ?>
	          <tr>

	            <td><?=$valor?></td>
              	<td class="options-width"></td>	            
              </tr>
	          
              <?php }
			  
			}else{?>
            
            <tr>
	            <td colspan="5" align="center">Nenhum registro cadastrado.</td>	            
            </tr>
            
            <?php } ?>
              
	          

            </table>
	        
          </form>
            
        </td>
    </tr>

</table>


