<div id="content-table-inner">
    <table border="0" cellpadding="0" cellspacing="0" id="paging-table" width="">
              <tr>
                <td align="center">
                <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '1'}, function(data) { $('#grid').html(data); });" class="page-far-left"></a> <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '<?=$this->anterior?>'}, function(data) { $('#grid').html(data); });" class="page-left"></a>
                  <div id="page-info">Página <strong><?=$this->pagina?></strong> / <?=$this->total_paginas?></div>
                  <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '<?=$this->proxima?>'}, function(data) { $('#grid').html(data); });" class="page-right"></a> <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '<?=$this->ultima?>'}, function(data) { $('#grid').html(data); });" class="page-far-right"></a></td>
              </tr>
      </table>
  <div class="clear"></div>
</div>

<form id="mainform" action="">
  <table width="100%" border="0" align="right" cellpadding="0" cellspacing="0" id="product-table">
	          <tr>
	            <th width="2%" class="table-header-check"><a id="toggle-all" ></a></th>
	            <th width="2%" class="table-header-options line-left"><a href="">Id</a></th>                
	            <th width="44%" class="table-header-repeat line-left minwidth-1"><a href="">Nome do franqueado</a></th>
	            <th width="47%" class="table-header-repeat line-left minwidth-1"><a href="">Slug</a></th>  
                <th width="5%" class="table-header-options line-left"><a href="">Acoes</a></th>
              </tr>
              
            <?php
			if($this->total_registros > 0)
			{
	        foreach ($this->lista as $chave => $valor){
	        ?>
	          <tr>
	            <td><input  type="checkbox" name="exclui[<?=$valor->ID_FRANQUEADO?>]" id="exclui[<?=$valor->ID_FRANQUEADO?>]"/></td>
                <td><?=$valor->ID_FRANQUEADO?></td>
	            <td><?=$valor->NOME_FRANQUEADO?></td>
	            <td></td>
                	<td class="options-width">
	            	<a href="javascript:void(0);" onclick="window.location='/admin/franqueados/editar/id/<?=$valor->ID_FRANQUEADO?>'" title="Editar" class="icon-1 info-tooltip"></a>
	            	<a href="javascript:deletar('<?=$valor->ID_FRANQUEADO?>');" title="Excluir" class="icon-2 info-tooltip"></a>
	            </td>	            
              </tr>
	          
              <?php }
			  
			}else{?>
            
            <tr>
	            <td colspan="5" align="center">Nenhum registro cadastrado.</td>	            
            </tr>
            
            <?php } ?>
              
	          

            </table>
	        
          </form>

	      
 <div id="content-table-inner">
    <table border="0" cellpadding="0" cellspacing="0" id="paging-table" width="">
              <tr>
                <td align="center">
                <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '1'}, function(data) { $('#grid').html(data); });" class="page-far-left"></a> <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '<?=$this->anterior?>'}, function(data) { $('#grid').html(data); });" class="page-left"></a>
                  <div id="page-info">Página <strong><?=$this->pagina?></strong> / <?=$this->total_paginas?></div>
                  <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '<?=$this->proxima?>'}, function(data) { $('#grid').html(data); });" class="page-right"></a> <a href="javascript:void(0);" onclick="javascript:$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '<?=$this->ultima?>'}, function(data) { $('#grid').html(data); });" class="page-far-right"></a></td>
              </tr>
      </table>
  <div class="clear"></div>
</div>