<?
 $auth = Zend_Auth::getInstance();
 $usuario_logado = $auth->getStorage()->read();
 //print_r($this->coments[0][0]->tb_glove_recados);
?>


<?php


if(count($this->coments[0]) > 0)
{
$cont = 0;
foreach($this->coments[0] as $chave => $valor)
{
?>


	<div class="linhaComentario" <?=$cont == 0 ? 'style="border-top:1px solid #E9E9E9;"' : ''?>>
    <img src="/thumbs/index/w/30/h/30/type/2/file/<?=$valor['ARQUIVO']?>" border="0" /> 
	<?=$valor['COMENTARIO']?> - <?=Lumine_Util::FormatDateTime($valor['DT_CADASTRO'], "%d/%m/%Y %H:%M")?>
    </div>


<?php
$cont++;
} ?>



<style>
.table_paginacao_coments a
{
	text-decoration:none;
	color:#000000;
}

.table_paginacao_coments td
{
text-decoration:none;
font-family:Verdana, Arial, Helvetica, sans-serif;
color:#CCCCCC;
font-size:8px;
padding-left:5px;
padding-right:5px;

}

.table_paginacao_coments td:hover
{
	
}
</style>



<?php 



$pags = $this->coments[1];


if($pags > 1):
$pgmod = 1;
$mod_atual = 1;
?>


<table border="0" class="table_paginacao_coments">
      <tr>
   
<?php



$p = isset($this->coments[3]) ? $this->coments[3] : 1;

if(isset($p)) {
	$p = $p;
} else {
	$p = 1;
}

$qnt = 8;
$inicio = ($p*$qnt) - $qnt;
$max_links = 8;

echo "<td><a href='javascript:void(0);' onclick=\"javascript:$.fn.InterfaceUsuario.metodos.getComentarios(1, '".$this->coments[0][0]['tb_glove_recados']."', '#placeHolderComentario".$this->coments[0][0]['tb_glove_recados']."', '#totalComentarios".$this->coments[0][0]['tb_glove_recados']."');\" title=\"Ir à primeira página\"> << </a> </td>";

for($i = $p-$max_links; $i <= $p-1; $i++) {
if($i <=0) {
} else {
echo "<td><a href='javascript:void(0);' onclick=\"javascript:$.fn.InterfaceUsuario.metodos.getComentarios('".$i."', '".$this->coments[0][0]['tb_glove_recados']."', '#placeHolderComentario".$this->coments[0][0]['tb_glove_recados']."', '#totalComentarios".$this->coments[0][0]['tb_glove_recados']."');\">".$i."</a></td> ";
}
}
	echo "<td>".$p."</td>";
	for($i = $p+1; $i <= $p+$max_links; $i++) {
	if($i > $pags)
	{
	
	}
	else
	{
		echo "<td><a href='javascript:void(0);' onclick=\"javascript:$.fn.InterfaceUsuario.metodos.getComentarios('".$i."', '".$this->coments[0][0]['tb_glove_recados']."', '#placeHolderComentario".$this->coments[0][0]['tb_glove_recados']."', '#totalComentarios".$this->coments[0][0]['tb_glove_recados']."');\">".$i."</a></td> ";
	}
	}
	echo "<td><a href='javascript:void(0);' onclick=\"javascript:$.fn.InterfaceUsuario.metodos.getComentarios('".$pags."', '".$this->coments[0][0]['tb_glove_recados']."', '#placeHolderComentario".$this->coments[0][0]['tb_glove_recados']."', '#totalComentarios".$this->coments[0][0]['tb_glove_recados']."');\" title=\"Ir à última página\"> >> </a></td> ";
	?>
</tr>
    </table>
 <?php endif; ?>

<?

}else{
?>
<div class="linhaComentario" style="border-top:1px solid #E9E9E9;">nenhum comentário</div>
<?php } ?>

