<form id="form1" name="form1" method="post">

   
<div id="editando">

<div id="left">
	INICIAL
	<ul>
        <!--<li>idade: <div><?=utf8_encode($this->perfil->DESCRICAO_idade)?></div></li>
        <li>altura: <div><?=utf8_encode($this->perfil->DESCRICAO_altura)?></div></li>
        <li>peso: <div><?=utf8_encode($this->perfil->DESCRICAO_peso)?></div></li>
        <li>tipo: <div><?=utf8_encode($this->perfil->DESCRICAO_tipo)?></div></li>
        <li>situação: <div><?=utf8_encode($this->perfil->DESCRICAO_situacao)?></div></li>
        <li>fumante: <div><?=utf8_encode($this->perfil->DESCRICAO_fumante)?></div></li>
        <li>buscando: <div><?=utf8_encode($this->perfil->DESCRICAO_interesse)?></div></li>
        <li>disponível: <div><?=utf8_encode($this->perfil->DESCRICAO_disponibilidade)?></div></li>
        <li>bebidas: <div><?=utf8_encode($this->perfil->DESCRICAO_bebidas)?></div></li>
        -->
    </ul>
    
</div>


<div id="right">
	
     <div class="form">

	<div class="campo">
       	  <label for="SENHA">Fale um pouco sobre você</label>
          <textarea name="SOBREMIM" rows="10" style="width:355px;" id="SOBREMIM"></textarea>
        </div>                                        
        
       	<div class="campo">
		<input type="submit" value="Finalizar">       
		</div>
        
        </div>
    
</div>

</div>



</form>



