<div id="page-heading">
	<h1><img src="/assets/admin/icones/icon1.png"> Tipo de conteúdo</h1>
</div>

<form id="form1" name="form1" enctype="application/x-www-form-urlencoded" action="/admin/modulos/salvar" method="post">

	<div id="tabs"> 
                <ul> 
                    <li><a href="#tabs-1">Tipo de conteúdo</a></li> 
                </ul> 
    
    <div id="validacao"></div>
    
    <div class="form">
       	
        <div id="tabs-1"> 
        
        
        <fieldset>
        <legend>Preencha o formulário</legend>
        
        <div class="linha">
        	
        
            
          <div class="elemento">
            	<label>Razão social:</label>
                <input name="RAZAO_SOCIAL" type="text" id="RAZAO_SOCIAL" size="60" value="<?=isset($this->modelo->RAZAO_SOCIAL) ? $this->modelo->RAZAO_SOCIAL : NULL?>" />
          </div>
          
          
            
          <div class="elemento">
            	<label>Nome fantasia:</label>
                <input name="NOME_FANTASIA" type="text" id="NOME_FANTASIA" size="56" value="<?=isset($this->modelo->NOME_FANTASIA) ? $this->modelo->NOME_FANTASIA : NULL?>" />
          </div>
          
          
           <div class="elemento">
            	<label>E-mail:</label>
                <input name="EMAIL" type="text" id="EMAIL" size="60" value="<?=isset($this->modelo->EMAIL) ? $this->modelo->EMAIL : NULL?>" />
          </div>
          
          
 
           <div class="elemento">
            	<label>Telefone:</label>
                <input name="TELEFONE" type="text" id="TELEFONE" size="56" value="<?=isset($this->modelo->TELEFONE) ? $this->modelo->TELEFONE : NULL?>" />
          </div>          
            
          
            
        </div>
            
                 
    	 <br style="clear:both" />
         
         <div class="linha">
         	 <div class="elemento">
             <input type="submit" value="Salvar" name="salvar" class="btnSalvar" />
             <input type="button" value="Voltar" name="salvar" onclick="window.location = '/<?=$this->modulo?>/<?=$this->controlador?>/'; " />           
             
             
             <input name="ID_EMPRESA" type="hidden" id="ID_EMPRESA" value="<?=isset($this->modelo->ID_EMPRESA) ? $this->modelo->ID_EMPRESA : NULL?>" readonly="readonly" />
             
             </div>
         </div>
        
    	    
    
</form>

<script>


function EnviaForm()
{
	$("#form1").submit(function () {

     	$.ajax({
             type: "POST",
             url: "/<?=$this->modulo?>/<?=$this->controlador?>/salvar",
             data: $("#form1").serialize(),
             dataType: "json",
             ContentType:	"text/json",
             success: function (data) 
             { 
			 	
			
				
 
				if(data.erro == "false")
				{					
					$.jGrowl(data.msg, { theme: 'ok'});
					
					window.location = '/<?=$this->modulo?>/<?=$this->controlador?>';
					
						
				}else if(data.erro == "valida")
				{
					$(".msg_validacao_input").remove();
					$.each(data.campos_erros, function(index, value) { 
						
						
						var input = $('#'+index).focus();				
						input.after("<div class=\"msg_validacao_input\"><div class=\"icone\"></div><div class=\"msg\">"+value+"</div></div>");

					 });
										 
					$.jGrowl(data.msg, { theme: 'alerta'});													
				}
				else if(data.erro == "erro")
				{
					$("#validacao").css("display", "none");
	                 $.jGrowl(data.msg, { theme: 'alerta'});
				}
       			
             },
			 error: function (data) 
			 {

				
			 }
         });
     
     return false;
 });
}



$(function() {

	 EnviaForm();	 
	 $( "#tabs" ).tabs();
	 
	 $("input")[0].focus();
	
});
</script>

