<h2>Resultado da sua busca (<?=$this->resultado['total']?>)</h2>

<?php 

 $profile = new Zend_Session_Namespace('perfil');
 $auth = Zend_Auth::getInstance();
 $usuario_logado = $auth->getStorage()->read();

?>

<?php
function formataNome($nome)
{	
	
	$nome = strtolower($nome);
	$preposicoes = array(" da ", " do ", " de ", " das ", " dos ");
	$nome = str_replace($preposicoes, " ", $nome);	
	$exp = explode(" ", $nome);
	if(count($exp) > 1)
	{
		$nome = ucfirst($exp[0]) . " " . (count($exp) >= 2 ? ($exp[1] == "" ? ucfirst(trim($exp[2])) : ucfirst(trim($exp[1]))) : ucfirst(trim($exp[1])));	
	}else
	{
		$nome = ucfirst($exp[0]);		
	}
	return $nome;
}
?>

<section id="sec-portfolio">
                <section id="portfolio">
                    <div class="flexslider">
                        <ul class="slides">
                            <li>
                                <ul class="portfolio-slide">
                                    
                                    <?php
								 if(count($this->resultado['retorno']) > 0)
								 {
								 foreach($this->resultado['retorno'] as $chave => $valor){
							
									 ?>
                                    <li>
                                        <figure> 
                                        
                                        <a href="/<?=$valor->SLUG_usuario?>-<?=$valor->ID_USUARIO_usuario?>" title="<?=ucfirst(strtolower($valor->NOME_usuario))?> <?=ucfirst(strtolower($valor->SOBRENOME_usuario))?>, <?=utf8_encode($valor->NOME_CIDADE_cidade)?>-<?=$valor->SGL_ESTADO_estado?> - Brasil "><img src="/thumbs/index/w/82/h/95/type/2/file/<?=isset($valor->ARQUIVO_fotoperfil) ? $valor->ARQUIVO_fotoperfil : ""?>" border="0" /></a>
                                        <a class="show-portfolio-text" href="#port1">
                                        
                                        <?=formataNome($valor->NOME_usuario . " " . $valor->SOBRENOME_usuario)?>
                                        
                                        </a>
    
									    <a href="javascript:void(0);" onclick="add('<?=$valor->ID_USUARIO_usuario?>', this);" rel="normal_request" id="<?=$valor->ID_USUARIO_usuario?>" class="btnAdd" title="Adicionar como amigo."><div style="height:20px;"><div style="float:left;"><img src="/assets/portal/default/images/btnAdd.png" border="0" style="padding-top:3px; padding-left:3px; " /></div> <div style="float:right; font-size:12px; margin-right:25px;"> adicionar</div></div></a>
                                        
                                        </figure>
                                        
                                        
                                             
                                    </li>
                                    
                                    
                                     <?php } 
									 }else{ ?>
									 
									 nenhum registro encontrado.
									 
									 <?php } ?>
                                    
                                   
                                </ul>
                            </li>
                        </ul>
                    </div>
                </section>
            </section>








<style>
.table_paginacao a
{
	text-decoration:none;
	color:#000000;
	padding:4px;
}

.table_paginacao td
{
padding-left: 5px;
padding-right: 5px;
text-decoration:none;
font-family:Verdana, Arial, Helvetica, sans-serif;
color:#CCCCCC;
font-size:10px;
border: 1px #999999 solid;
padding:2px;
}

.table_paginacao td:hover
{
background-color:#ffffff;

}
</style>


<div style="width:100%; min-height:1px; overflow:hidden; padding-top:30px;">

<?php 



$pags = $this->resultado['total_paginas']; 
if($pags > 1):
$pgmod = 1;
$mod_atual = 1;
?>


<table border="1" class="table_paginacao">
      <tr>
   
<?php



$p = isset($this->resultado['paginaatual']) ? $this->resultado['paginaatual'] : 1;

if(isset($p)) {
	$p = $p;
} else {
	$p = 1;
}

$qnt = 8;
$inicio = ($p*$qnt) - $qnt;
$max_links = 8;

echo "<td><a href=\"javascript:void(0);\" onclick=\"javascript:resultado(1)\" title=\"Ir à primeira página\"> << </a> </td>";

for($i = $p-$max_links; $i <= $p-1; $i++) {
if($i <=0) {
} else {
echo "<td><a href=\"javascript:void(0);\" onclick=\"javascript:resultado(".$i.")\">".$i."</a></td> ";
}
}
	echo "<td class=\"ativa\" style=\"padding:4px;\">".$p."</td>";
	for($i = $p+1; $i <= $p+$max_links; $i++) {
	if($i > $pags)
	{
	
	}
	else
	{
		echo "<td><a href=\"javascript:void(0);\" onclick=\"javascript:resultado(".$i.")\">".$i."</a></td> ";
	}
	}
	echo "<td class=\"classe_td_no_border\"><a href=\"javascript:void(0);\" onclick=\"javascript:resultado(".$pags.")\" title=\"Ir à última página\"> >> </a></td> ";
	?>
</tr>
    </table>
 <?php endif; ?>


<script>
  
  
  	function add(id, obj)
	{
			
				$.ajax({
					 type: "POST",
					 url: "/conta/addamigo",
					 data: {amigo : id},
					 dataType: "json",
					 ContentType:	"text/json",
					 success: function (data) 
					 { 
		 
						if(data.erro == "false")
						{					
						
							
							window.parent.parent.$().toastmessage('showToast', {
								text     :  data.msg,
								stayTime   : 6000,
								type     : 'success'
							});		
							
						
							$(obj).click(function(){
								return false;	
							});
							
							$(obj).find("img:first").attr("src", "/assets/portal/default/images/btnAdd.jpg");
						
						if(socket != null)
						{
		
							socket.emit('AmigoAdd', { tipo: 'AmigoAdd', data : { data : id }});	
						}
		
								
						
						}else if(data.erro == "true")
						{
							window.parent.parent.$().toastmessage('showToast', {
								text     : data.msg,
								stayTime   : 60000,
								type     : 'warning'
							});				
						}
						
					 },
					 error: function (data) 
					 {
		
						
					 }
				 });
	}
	
    $(document).ready(function(){		
		
	});



</script>


