<?php $this->placeholder('multiscripts')->captureStart();?>


<style>
body
{
	margin: 0px 0px 0px 0px;
}
#main {
	  padding-top: 0;
}
</style>

<?php $this->placeholder('multiscripts')->captureEnd() ?>

<script>
  
	   $(document).ready(function(){
		
				
		$(".btnAceitar").bind("click", function(ui, e)
		{
			var id = $(this).attr("id");
			
				$.getJSON('/conta/confirmaamigo',
		
					{ amigo : id, status : 1}
				,
				function (data) 
				{ 
					$("#linha"+id).fadeOut();
					
					
					/*window.parent.socket.disconnect();
					
				    window.parent.socket =   window.parent.io.connect(window.parent.url, { 'max reconnection attempts': 100, 'auto connect': true });*/
					
					
					 var amigos = window.parent.$.fn.interfaceChat.metodos.amigos();
					 amigos.success(function (data){					
							var listaamigos = window.parent.$.fn.interfaceChat.metodos.listaamigos(data);
					  });
					

					/*var interfaceChat =  window.parent.$("body").interfaceChat
					(
						{
							url: url,
							onPegaMeusDados: function (data) {
								 window.parent.socket.emit('adduser', { usuario: data, namespace: namespace });
							},
							onAbreJanela: function (data) {
								//$.fn.interfaceChat.metodos.registraSessaoChat(data.destinatario);
							},
							onDigitandoMensagem: function (data) {
								 window.parent.socket.emit('digitandomsg', { remetente: data.remetente, destinatario: data.destinatario, sala: data.sala, msg: data.msg });
							},
							onDigitandoMensagemLimpa: function (data) {
								 window.parent.socket.emit('digitandomsglimpa', { remetente: data.remetente, destinatario: data.destinatario, sala: data.sala, msg: data.msg });
							},
							onEnviaMensagem: function (data) {
								socket.emit('sendchat', { remetente: data.remetente, destinatario: data.destinatario, sala: data.sala, msg: data.msg });
							}
						}
					);*/
							
					
					
					
					var atual = parseInt(window.parent.$("#contaSolicitacoes").html());
					var diminui = (atual - 1);	
					if(diminui > 0)
					{
						window.parent.$("#contaSolicitacoes").html(diminui.toString())
					}else
					{
							window.parent.$("#contaSolicitacoes").html("0")
					}
					
					window.parent.parent.$().toastmessage('showToast', {
						text     :  data.msg,
						stayTime   : 6000,
						type     : 'success'
					});		
					
					
					
				});	
		});
		
		
		$(".btnRec").bind("click", function(ui, e)
		{
			var id = $(this).attr("id");
			
				$.getJSON('/conta/confirmaamigo',
		
					{ amigo : id, status : 0}
				,
				function (data) 
				{ 
					$("#linha"+id).fadeOut();
					
					
					var atual = parseInt(window.parent.$("#contaSolicitacoes").html());
					var diminui = (atual - 1);	
					if(diminui > 0)
					{
						window.parent.$("#contaSolicitacoes").html(diminui.toString())
					}else
					{
							window.parent.$("#contaSolicitacoes").html("0")
					}
					
					window.parent.parent.$().toastmessage('showToast', {
						text     :  data.msg,
						stayTime   : 6000,
						type     : 'success'
					});		
					
				});	
		});
		
    });

</script>
<div style="min-height:200px;">
<form id="form1" name="form1" method="post">
<h3>Solicitações de amizades <a href="/conta/solicitacoes"><img src="/assets/btnRefresh.png" width="16" height="16" border="0" /></a></h3>
<hr />

<table width="470" cellspacing="5">

<?php
function formataNome($nome)
{	
	$nome = strtolower($nome);
	$preposicoes = array(" da ", " do ", " de ", " das ", " dos ");
	$nome = str_replace($preposicoes, " ", $nome);	
	$exp = explode(" ", $nome);
	if(count($exp) > 1)
	{
		$nome = ucfirst($exp[0]) . " " . (count($exp) >= 2 ? ($exp[1] == "" ? ucfirst($exp[2]) : ucfirst($exp[1])) : ucfirst($exp[1]));	
	}else
	{
		$nome = ucfirst($exp[0]);		
	}
	return $nome;
}
?>

<?

/*echo "<pre>";
print_r($this->modelo);
echo "</pre>";*/

/*die();*/
$i=1;
if(count($this->modelo) > 0)
{
foreach($this->modelo as $chave => $valor)
{
	
if($i % 2 == 0)
{
	$cor = "#FFFFFF";
}else
{
	$cor = "#f9f9f9";	
}
?>

<tr id="linha<?=$valor->tb_sys_usuario?>" bgcolor="<?=$cor?>">
	<td width="22" align="center" valign="middle">
    <a title="<?=formataNome($valor->NOME . " " . $valor->SOBRENOME)?>" href="javascript:chamaUrl('/<?=$valor->SLUG?>-<?=$valor->tb_sys_usuario?>')"><img src="/thumbs/index/w/80/h/80/type/2/file/<?=$valor->ARQUIVO?>" border="0" /></a>
    </td>
   	<td width="250" align="center" valign="middle"><br /><br /> <a title="<?=formataNome($valor->NOME . " " . $valor->SOBRENOME)?>" href="javascript:chamaUrl('/<?=$valor->SLUG?>-<?=$valor->tb_sys_usuario?>')"><?=formataNome($valor->NOME . " " . $valor->SOBRENOME)?></a></td>
    <td width="79" align="center" valign="top"><input class="btnAceitar" id="<?=$valor->tb_sys_usuario?>"  type="button" style="border-radius: 8px; min-width:10px; height:33px; font-size:13px; cursor:pointer; background-color:#009999; color:#FFFFFF; border:none;" value="confirmar" /></td>
    <td width="74" align="center" valign="top"><input class="btnRec" id="<?=$valor->tb_sys_usuario?>"  type="button" style="border-radius: 8px; min-width:10px; height:33px; font-size:13px; cursor:pointer; background-color:#009999; color:#FFFFFF; border:none;" value="recusar" /></td>
</tr>

<?
$i++;
}
}else{
?>
<p align="center">nenhuma solicitação de amizade pendente. <br /><br /><br /><a onclick="window.parent.location = '/conta/busca';" href="javascript:void(0);"><b>Clique aqui para buscar novas amizades</b></a></p>
<?php } ?>
</table>
</form>
</div>


