<div id="page-heading">
	<h1><img src="/assets/admin/icones/icon1.png"> Banners</h1>
</div>


    
<table width="100%" border="0" cellpadding="0" align="center">
    <tr>
    	<td width="50%" valign="top">
        
        
       
        
        
        </td>
    	<td width="4%" valign="top">&nbsp;</td>
    	<td width="46%" align="right" valign="top">
        
          <?php
		 if(count($this->aplicacoes) > 0){
		 ?>  
         
        
            	<label for="tb_sys_aplicacao">Filtrar por categoria:</label>
                <select name="tb_sys_aplicacao" id="tb_sys_aplicacao">
				<option value="">mostrar todos...</option>                
                <?php 
				foreach($this->aplicacoes as $chave => $valor){
				?>
                <option value="<?=$valor->ID_APLICACAO?>"><?=$valor->DESCRICAO?></option>
                <?php } ?>
                </select>
                   
         
         <?php }else{ ?>
         		
               <input type="hidden" name="tb_sys_aplicacao" id="tb_sys_aplicacao" value="<?=$this->aplicacoes->ID_APLICACAO?>">
                
         <?php } ?> 
        
		</td>
    </tr>
    <tr>
    	<td colspan="3" valign="top">
   	    	<div id="grid"></div>
        </td>
    </tr>

</table>


<script>

	function deletar_selecionados()
	{	
		jConfirm('Confirmar exclusão?', 'Confirmar ação', function(r) {
			if( r ){ 
				$.ajax({
				 type: "POST",
				 url: "/<?=$this->modulo?>/<?=$this->controlador?>/excluirselecionados",
				 data: $("#mainform").serialize(),
				 dataType: "json",
				 ContentType:	"text/json",
				 success: function (data) 
				 { 
					if(data.erro == "false")
					{					
						$.jGrowl(data.msg, { theme: 'ok'});	
						$.post('/admin/modulos/grid', { pagina: '1'},  function(data) { $('#grid').html(data); });
						
					}
					else if(data.erro == "true")
					{
						 $.jGrowl(data.msg, { theme: 'alerta'});
					}
					
				 }
			 }); 
		 };
		});
	}
	
	
	function deletar(id)
	{	
		jConfirm('Confirmar exclusão?', 'Confirmar ação', function(r) {
			if( r ){ 
				$.ajax({
				 type: "POST",
				 url: "/<?=$this->modulo?>/<?=$this->controlador?>/excluir/id/",
				 data: { id: id},
				 dataType: "json",
				 ContentType:	"text/json",
				 success: function (data) 
				 { 
					if(data.erro == "false")
					{					
						$.jGrowl(data.msg, { theme: 'ok'});	
						$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: '1'},  function(data) { $('#grid').html(data); });
						
					}
					else if(data.erro == "erro")
					{
						 $.jGrowl(data.msg, { theme: 'alerta'});
					}
					
				 }
			 }); 
		 };
		});
	}
	
	
	


$(document).ready(function () {
	grid(1);
	
	$('#tb_sys_aplicacao').bind('change', function(ui, e){
		grid(1);
	})
});	

function grid(pagina)
{
	var app = $("#tb_sys_aplicacao").val();
	
$.post('/<?=$this->modulo?>/<?=$this->controlador?>/grid', { pagina: pagina, app: app}, function(data) { $('#grid').html(data); });	
	
}
</script>
