<?php $this->placeholder('multiscripts')->captureStart();?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
<!--<script src="http://69.194.199.162:8080/socket.io/socket.io.js"></script>-->
<script src="http://glove:8080/socket.io/socket.io.js"></script>

<script>
 

var socket = null;
var voce = null;
//var url = 'http://69.194.199.162:8080';
var url = 'http://glove:8080';
//var url = '/';


$(document).ready(function() {
	
		socket = io.connect(url);
		//socket.socket.reconnect(); para reconectar
	
		
		socket.on('connect', function(){ 
		
		console.log("conectou..."); 
		

			
			socket.emit('adduser', { usuario: window.parent.frames["principal"].cliente.promptName() });
		
		});
		socket.on('connecting', function (){  console.log("conectando...");  }) 
		socket.on('connect_failed', function () { console.log("conexão falha...");  })
		socket.on('error', function () { console.log("erro ocorrido...");  })
		socket.on('reconnect_failed', function () { console.log("reconexão falhada...");  })		
		socket.on('reconnect', function () { console.log("reconectou...");  })				
		socket.on('reconnecting', function () { console.log("reconectando...");  })						
		
		socket.on('disconnect', function(){
			
			console.log('desconectou');
			
		});
		
		
		socket.on('listaconectados', function(data){
			
			window.parent.frames["principal"].cliente.conectados(data);
			console.log(data);
			
		});
		
		socket.on('sendchat', function (data) {
			console.log(data);
		});
		
		
		
		socket.on('SERVIDOR', function(data){
			
			console.log(data);
			
		});
		
		
		
		
	
});



</script>


<?php $this->placeholder('multiscripts')->captureEnd() ?>


