<?php $this->placeholder('multiscripts')->captureStart();?>

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
-->


</script>


<?php $this->placeholder('multiscripts')->captureEnd() ?>




<FRAMESET ROWS="0%, 100%" border="0" frameSpacing="0" noresize>
<FRAME SRC="http://glove/chat/connect">
<FRAME SRC="http://glove/chat/meio" id="principal" NAME="principal">

<NOFRAME>
<BODY>

</BODY>
</NOFRAME>
</FRAMESET><noframes></noframes>
